$schema: http://azureml/sdk-2-0/Schedule.json
name: energy_demand_batch_monitoring
description: Energy demand model monitoring for batch endpoint

trigger:
  type: recurrence
  frequency: day  # Can be minute, hour, day, week, month
  interval: 1
  schedule:  # In UTC 
    hours: 9
    minutes: 45

create_monitor:

  compute:
    instance_type: "standard_e4s_v3"  # Spark compute for monitoring job
    runtime_version: "3.2"

  monitoring_signals:

    ########################
    ##  Prediction drift  ##
    ########################
    batch_prediction_drift:
      type: prediction_drift
      target_dataset:
         dataset:
            input_dataset:
               path: azureml:energy-batch-preds:1
               type: uri_folder
            dataset_context: model_outputs
            pre_processing_component: azureml:custom_preprocessor:1.0.0
      baseline_dataset:
        input_dataset:
          path: azureml:energy-demand-training:1
          type: uri_folder
        dataset_context: test
        pre_processing_component: azureml:custom_preprocessor:1.0.0
      metric_thresholds:
        - applicable_feature_type: numerical
          metric_name: jensen_shannon_distance
          threshold: 0.01
        - applicable_feature_type: categorical
          metric_name: pearsons_chi_squared_test
          threshold: 0.02


    ########################
    ##     Data drift     ##
    ########################
    # batch_data_drift: # monitoring signal name, any user defined name works
    #   type: data_drift
    #   # target_dataset is optional. By default target dataset is the production inference data associated with Azure Machine Learning online endpoint
    #   baseline_dataset:
    #     input_dataset:
    #       path: azureml:my_model_training_data:1 # use training data as comparison baseline
    #       type: mltable
    #     dataset_context: training
    #     target_column_name: fraud_detected
    #   features: 
    #     top_n_feature_importance: 20 # monitor drift for top 20 features
    #   metric_thresholds:
    #     - applicable_feature_type: numerical
    #       metric_name: jensen_shannon_distance
    #       threshold: 0.01
    #     - applicable_feature_type: categorical
    #       metric_name: pearsons_chi_squared_test
    #       threshold: 0.02

    ########################
    ##    Data quality    ##
    ########################
    # advanced_data_quality:
    #   type: data_quality
    #   baseline_dataset:
    #     input_dataset:
    #       path: azureml:energy-demand-training:1
    #       type: uri_folder
    #     dataset_context: training
    #   metric_thresholds:
    #     - applicable_feature_type: numerical
    #       metric_name: null_value_rate
    #       threshold: 0.05
    #     - applicable_feature_type: categorical
    #       metric_name: out_of_bounds_rate
    #       threshold: 0.05

    ###########################
    ##  Feature attribution  ##
    ###########################
    # feature_attribution_drift_signal:
    #   type: feature_attribution_drift
    #   target_dataset:
    #      dataset:
    #         input_dataset:
    #            path: azureml:my_model_production_data:1
    #            type: uri_folder
    #         dataset_context: model_inputs_outputs
    #   baseline_dataset:
    #     input_dataset:
    #       path: azureml:my_model_training_data:1
    #       type: mltable
    #     dataset_context: training
    #     target_column_name: fraud_detected
    #   model_type: classification
    #   # if no metric_thresholds defined, use the default metric_thresholds
    #   metric_thresholds:
    #      threshold: 0.9

      # features: # monitor data quality for 3 individual features only
      #   - feature_A
      #   - feature_B
      #   - feature_C


  # alert_notification:
  #   emails:
  #     - asd@asd.com
