$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue-dp
endpoint_name: energy-demand-online-endpoint
model: azureml:energy-model@latest
instance_type: Standard_D2a_v4
instance_count: 1

code_configuration:
  code: .
  scoring_script: score.py
environment: 
  conda_file: conda.yml
  image: mcr.microsoft.com/azureml/mlflow-ubuntu20.04-py38-cpu-inference:latest

data_collector:
  collections:
    model_inputs:
      enabled: 'True'
      data:
        name: energy-odp-inputs
        path: azureml://datastores/mdc_store/paths/energy-demand-online-endpoint/blue-dp/model_inputs
        # version: 1
    model_outputs:
      enabled: 'True'
      data:
        name: energy-odp-outputs
        path: azureml://datastores/mdc_store/paths/energy-demand-online-endpoint/blue-dp/model_outputs
        # version: 1
