$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: defstore-dp
endpoint_name: energy-demand-online-endpoint
model: azureml:energy-model@latest
instance_type: Standard_DS3_v2
instance_count: 1

code_configuration:
  code: .
  scoring_script: score.py
environment: 
  conda_file: conda.yml
  image: mcr.microsoft.com/azureml/mlflow-ubuntu20.04-py38-cpu-inference:latest

data_collector:
  collections:
    model_inputs:
      enabled: 'True'
    model_outputs:
      enabled: 'True'
