name: cli-batch-monitor

on:
  workflow_dispatch:
    inputs:
      cli_version:
        description: "CLI ml extension version"
        type: string
        required: false
        default: 2.19.1


jobs:

  batch_monitor:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      #############
      ##  Setup  ##
      #############
      - name: "[Setup] Install CLI ml ${{ inputs.cli_version }}"
        run: |
          az extension add --name ml --version ${{ inputs.cli_version }} -y
      - name: "[Setup] Azure login"
        uses: azure/login@v1
        with:
          creds: '{
            "clientId": "${{ secrets.AML_SP_CLIENT }}",
            "clientSecret": "${{ secrets.AML_SP_SECRET }}",
            "subscriptionId": "${{ secrets.AML_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AML_TENANT_ID }}"
          }'
      - name: "[Setup] Set default AML workspace"
        run: az configure --defaults workspace="${{ vars.AML_WORKSPACE_NAME }}" group="${{ vars.AML_RG_NAME }}"
      - name: "[Setup] Checkout repo"
        uses: actions/checkout@v4


      #############################
      ##  Deploy batch monitor  ##
      #############################
      # - name: "Deploy dataprep component"
      #   run: az ml component create --file $GITHUB_WORKSPACE/deployment/batch/monitoring-dataprep-component.yml --debug
      - name: "Deploy monitor"
        run: az ml schedule create --file $GITHUB_WORKSPACE/deployment/batch/batch-monitor.yml --debug
