name: invoke-batch-inference

on:
  workflow_dispatch:
  # schedule:  # UTC
  #   - cron: "30 9 * * *"  # min hour dom month dow

jobs:

  invoke_inference:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      #############
      ##  Setup  ##
      #############
      - name: "[Setup] Install CLI ml 2.19.1"
        run: |
          az extension add --name ml --version 2.19.1 -y
      - name: "[Setup] Azure login"
        uses: azure/login@v1
        with:
          creds: '{
            "clientId": "${{ secrets.AML_SP_CLIENT }}",
            "clientSecret": "${{ secrets.AML_SP_SECRET }}",
            "subscriptionId": "${{ secrets.AML_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AML_TENANT_ID }}"
          }'
      - name: "[Setup] Set default AML workspace"
        run: az configure --defaults workspace="${{ vars.AML_WORKSPACE_NAME }}" group="${{ vars.AML_RG_NAME }}"
      - name: "[Setup] Checkout repo"
        uses: actions/checkout@v4


      ##########################################
      ##  Invoke batch endpoint & deployment  ##
      ##########################################
      - name: "Invoke batch endpoint"
        run: |
          # Make predictions for tomorrow - simulating as if 2016 was current year
          year="2016"
          month=$(date -d "+1 day" +"%m")
          day=$(date -d "+1 day" +"%d")
          filepath="$year/$month/$day"
          filename=$year$month$day".csv"
          datapath="azureml://datastores/data/paths/energy_demand_azuremlexamples"
          az ml batch-endpoint invoke \
            --name energy-demand-batch-endpoint --deployment-name batch-dp \
            --input-type uri_folder \
            --input $datapath/daily_features_data/$filepath/energy_features_$filename \
            --output-path $datapath/daily_preds/$filepath \
            --debug
